language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
script:
- npm run eslint
- npm run build
deploy:
  provider: heroku
  edge: true
api_key:
    secure: $API_KEY
app: hacker-news-srr
on:
  repo: sivasankar9/react-hacker-news-ssr
  branch: master
