language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run eslint
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: AsNSj/9Xa8oXQ0hS9igoRRONVDI4DknBeNhplr2ofvYHIfXPYj87xxy//epQPocmqY21LbNUJ1bEZUCGjTc9SzgfaRR+9fuPQB2f8+OP7WWYxmqMjEgEi8rQNAtcEVqQ6lt96UOP+d8mPbv2W6LAZQRNx0usrz7zD6x3AmH5NKqq0+ihwCA+5GHFA2fQIV4Eh8U78/f1cAnBmZFcHwpC63jk+ncXqXgERCitWnyl1FnmZwm5MMTIA/2p5wA2L8IquG1ooR99rqWs95bhkX4+OizBTBfSIVq5xty6bXk0Sknpf63hyeQR2HFzE+Z7nWwGdP3ojLJ7Jcjh8HWPlyOTLhFfmGrjRTe5kcduaTe1jHMyCGkhO+9Ug1reSHBYuPBLSgdacGdEjwfS3ziSd2weiuZIWdxPrifupL4nw3vPC2vuYBBFoh+nUISSLYdyvfNNaOFIc5X6p5aHGneZu79UqV8EIJ0HweToKrXFa7DjhcI5W7eyNCQ0qtmE2mp3lJSCL6kH2+4342Q+v45hkFTJ8EMPkZ8jV1eO7fvNPh/WO0p9pb/QnQEiR0nk+NHQmBMB6VQWHgQQDv1NRHYBy1vTZZD2aPFNnCuvyeyAM5PL7oSLcpSY5QJCfRwexV6i6ik3fJmsFArVRnaTszOwF8QUqOSbJ+pGN2kC8KNzpe57BY8=
app: hacker-news-srr
true:
  repo: sivasankar9/hacker-news-srr
  branch: master
